alertlogic/paws-collector

- extensions/okta/okta_collector.js
- extensions/okta/package.json
> Fix paws-collector dependency

- collectors/okta/package.json
- collectors/okta/test/okta_test.js
- package.json
- paws_collector.js
- test/paws_test.js
More `extensions` -> `collectors` renaming required.
> More renaming

- cfn/auth0-collector.template
- collectors/auth0/LICENSE
- collectors/auth0/Makefile
- collectors/auth0/auth0_collector.js
- collectors/auth0/index.js
- collectors/auth0/package.json
Implement an Auth0 log collector using the `paws-collector` library/framework.
> Initial Auth0 collector implementation

- .travis.yml
- collectors/okta/index.js
> Cleanup okta index.js

- package.json
- paws_collector.js
> Update dependencies in PAWS

- collectors/auth0/package.json
- collectors/okta/package.json
Update dependencies for collectors
> Update collectors dependencies.

- package.json
- paws_collector.js
Override `getProperties()` to pass additional parameters for registration/checkin.
> update deps. Override getProperies.

- collectors/auth0/package.json
- collectors/okta/package.json
> Update okta and auth0 deps

- .npmignore
- collectors/okta/local/events/event.json
- collectors/okta/local/events/event_poll.json
- collectors/okta/local/events/event_register.json
- collectors/okta/local/sam-template.yaml
- local/events/event.json
- local/events/event_deregister.json
- local/events/event_register.json
- local/sam-template.yaml
- package.json
Cleanup some test data.
Add `.npmignore`.
> Repo cleanup, NPM package cleanup

- collectors/auth0/auth0_collector.js
> Fix Auth0 syntax error

- collectors/auth0/auth0_collector.js
Initial fetch based on timestamp was not in the correct sort order.
Include option to sort by date ascending.
> Sort by date ascending in initial fetch

- collectors/auth0/al-auth0-collector.json
- collectors/o365/al-o365-collector.json
- collectors/okta/al-okta-collector.json
- collectors/template/collector.json
- create-collector.js
There needed to be json configs in the collector for the purposes of deploying via the new pipeline
Add json configs to existing collectors and add generation of the config file to the generator script.
> Json configs

- collectors/template/collector.js.template
- collectors/template/index.js.template
- collectors/template/package.json.template
I noticed some fixes were needed for the template after building out Google Cloud Collector.
Make those fixes.
> Template fixes

- cfn/okta-collector.template
- collectors/okta/okta_collector.js
- package.json
- paws_collector.js
There was an issue with the reg body that paws was sending to azcollect
Fixed this issue and cleaned up okta collector.
> Fix registration for paws generally and okta

- cfn/o365-collector.template
- collectors/o365/test/o365_test.js
- collectors/o365/test/o365managment_test.js
some stuff needed cleaned up
♫ Scrub scrub here
Scrub scrub there 
change that function clause
it's time to clean the codebase up
in the merry old land of paws ♫
> General Cleanup

- collectors/okta/package.json
- collectors/okta/test/okta_test.js
needed some tests for the okta collector
added at least a thin spread of code coverage for the okta collector.
> Okta tests

- collectors/auth0/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/template/package.json.template
> Update paws version

- test/paws_mock.js
- test/paws_test.js
Base paws-collector had low test code coverage %
Test all the things, including the thrown errors for interfaces that are not implemented in paws collectors.
> Additional code coverage

- cfn/o365-collector.template
- collectors/o365/lib/o365_mgmnt/index.js
- collectors/o365/lib/o365_mgmnt/o365management.js
- collectors/o365/local/events/event_poll.json
- collectors/o365/local/run-sam.sh
- collectors/o365/local/sam-template.yaml
- collectors/o365/o365_collector.js
- collectors/o365/package-lock.json
- collectors/o365/test/o365_mock.js
- collectors/o365/test/o365_test.js
- collectors/o365/test/o365managment_test.js
some fixes for o365 in hopes of it being read for SKO. will continue tomorrow.
added:
- fix for start times that aremore recent for 24 hours
- some pagination for list content
> Do some fixes for o365 collector

- collectors/okta/okta_collector.js
- collectors/okta/test/okta_test.js
handle all cases for initial states:
1. **startDate** < now - pollInterval
1. now - pollInterval < **startDate** < now
1. **startDate** = now
> Fix initial states for Okta collector.

- collectors/auth0/package.json
- collectors/auth0/test/auth0_mock.js
- collectors/auth0/test/auth0_test.js
Add some tests for Auth0 collector
> Auth0: Add some tests

- cfn/paws-collector.template
- package.json
- paws_collector.js
- test/paws_test.js
Try and simplify these api keys
Switch it all over the param store.
> Go big or go home an refactor completely for param store

- collectors/auth0/package.json
- collectors/auth0/test/auth0_mock.js
- collectors/auth0/test/auth0_test.js
> Use latest paws with SSM

- cfn/paws-collector.template
We were running into name constraint violations
make some CFN template.
> Queue name change

- README.md
- cfn/paws-collector.template
- collectors/template/package.json.template
- create-collector.js
- package.json
- paws_collector.js
- test/paws_mock.js
- test/paws_test.js
Add helper function for collector to report throttling.
Bonus: some collector template fixes.
> Add paws throttling report helper

- collectors/template/package.json.template
- package.json
needed better error handling for paws collectors
Update the deps to include that better error handling.
> Update al-aws-collector-js dependency

- collectors/googlestackdriver/test/mock.js
- collectors/googlestackdriver/test/test.js
> Add tests and code coverage to stackdriver

- create-collector.js
What was fixed? - root cause
How it was fixed? - implementation details
> fix template create path

- cfn/paws-collector.template
- encrypted credentials not returned by custom resource on stack update
- add clause to handle update events
> return encrypted credentials on stack update

- collectors/o365/Makefile
- collectors/o365/local/events/event_poll.json
- collectors/o365/local/run-sam.sh
- collectors/o365/local/sam-template.yaml
- collectors/o365/package.json
Needed to update the local env stuff and the make sure the package was being built correctly.
fix makefile and local env stuff
> fix local invocation stuff and makefile

- package.json
- paws_collector.js
- test/paws_test.js
Report collection delay metric based on collector state.
> Report collection delay metric

- package.json
- paws_collector.js
- bad return value for collectionStateArray function led to registration failing intermittently 
- fix the return to allow registration to succeed
> Batch splitting fix

- package.json
- paws_collector.js
Report invocation errors for paws collectors.
> Report errors during invocation

- package.json
- paws_collector.js
Update deps to fix collector status reporting
> Update deps for status reporting

- collectors/gsuite/cfn/gsuite-collector.template
- No custom endpoint currently required for gsuite collectors 
- remove PawsEndpoint parameter from cfn stack
> Remove GSuite Paws Endpoint Parameter

- package.json
- paws_collector.js
Default health and stats checks to `[]`
> Default checks to []

- collectors/okta/health_checks.js
- collectors/okta/package.json
- collectors/okta/test/okta_test.js
Okta health check function was broken
Fix okta health check function. 
Use `al-collector-js.RestServiceClient`.
Update tests.
> Fix okta health checks

- .travis.yml
- cfn/paws-collector.template
Switch collector lambdas to node 12
> Switch to node 12

- collectors/salesforce/cfn/salesforce-collector.template
- collectors/salesforce/collector.js
- collectors/salesforce/local/sam-template.yaml
- collectors/salesforce/package.json
- collectors/salesforce/test/salesforce_mock.js
- collectors/salesforce/test/salesforce_test.js
- collectors/salesforce/utils.js
Code refactored request to rest service Client.
> Salesforce v2

- collectors/auth0/al-auth0-collector.json
- collectors/googlestackdriver/al-googlestackdriver-collector.json
- collectors/gsuite/al-gsuite-collector.json
- collectors/o365/al-o365-collector.json
- collectors/okta/al-okta-collector.json
- collectors/salesforce/al-salesforce-collector.json
- collectors/template/collector.json
> Move all collectors config to node 12

- collectors/auth0/auth0_collector.js
- collectors/auth0/package.json
Sometimes customers input endpoint with `http` prefix
Trim endpoint to domain name.
Update deps.
> Update deps. Fix endpoint

- collectors/gsuite/cfn/gsuite-collector.template
- collectors/gsuite/collector.js
- collectors/gsuite/package.json
- collectors/gsuite/test/gsuite_mock.js
- collectors/gsuite/test/gsuite_test.js
scopes are being fed by azcollect in JSON array format
have collector handle this list of scopes.
> Fix scope permissions

- .npmrc
- package.json
- paws_collector.js
Wrong collector version is reported because the lib version is used
Pass actual collector version from a collector
Update deps
> Update deps. Use actual collector version.

- collectors/auth0/.npmrc
- collectors/auth0/auth0_collector.js
- collectors/auth0/package.json
- collectors/okta/.npmrc
- collectors/okta/okta_collector.js
- collectors/okta/package.json
- collectors/template/.npmrc
- collectors/template/collector.js.template
Update okta and auth0 with latest fixes to report proper version.
> Update Auth0 and Okta

- collectors/gsuite/cfn/gsuite-collector.template
- malformed json in gsuite cfn template
- fix json
> Fix GSuite template json

- collectors/gsuite/package.json
- bump gsuite package.json version
> bump gsuite package version

- collectors/googlestackdriver/collector.js
- collectors/googlestackdriver/package.json
- collectors/gsuite/collector.js
- collectors/gsuite/package.json
- collectors/o365/o365_collector.js
- collectors/o365/package.json
- collectors/salesforce/collector.js
- collectors/salesforce/package.json
- collectors/template/collector.js.template
- collectors/template/package.json.template
o365, gcp, gsuite, sfdc so not report actuall collector version
Use latest deps to report actual collector package version.
> Upd collector version for o365, gcp, gsuite, sfdc

- collectors/googlestackdriver/package.json
- collectors/o365/package.json
New tags will be published with the next release.
> Align package versions with tags

- cfn/paws-collector.template
- package.json
- paws_collector.js
- test/paws_test.js
Need to give the collector programmatically set its own api key param
Implement that functionality.
> add functionality to set param

- package.json
- paws_collector.js
need to set Overwrite param in the SSM call. this was not commited and didnt make it into the previousPR
add missing param
> Paws 1.1.9

- package.json
- paws_collector.js
- ps_spec.yml
Paws collector continue collection even if registration fails.
Make sure collection is not happening without `collector_id`.
Periodically reregister collector during checkin if it is unregistered.
> Do not run collection if unregistered

- collectors/o365/lib/o365_mgmnt/o365management.js
- collectors/o365/package.json
- collectors/o365/test/o365managment_test.js
Pre formed urls were having their publisher id incorrectly appended to the end of the url.
Check if pre formed url already has a query string an append accordingly.
> Pagination fix

- collectors/o365/o365_collector.js
- collectors/o365/package.json
tsPaths and msgTypePaths were switched in o365 collector.
Switch them back.
> fix switched timestamp paths

- README.md
- ps_spec.yml
> Fix alps builds

- package.json
- paws_collector.js
> rename tag for applicationid

- collectors/auth0/index.js
- collectors/auth0/package.json
- collectors/carbonblack/index.js
- collectors/carbonblack/package.json
- collectors/googlestackdriver/index.js
- collectors/googlestackdriver/package.json
- collectors/gsuite/index.js
- collectors/gsuite/package.json
- collectors/o365/index.js
- collectors/o365/package.json
- collectors/okta/index.js
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/index.js
- collectors/sentinelone/package.json
- collectors/template/index.js.template
- collectors/template/package.json.template
Adding DD handler to collectors
> DD handler to all collectors

- package.json
- paws_collector.js
- test/paws_mock.js
Add stackname and check for handler
> Add stackname and check for handler

- collectors/auth0/auth0_collector.js
- collectors/auth0/cfn/auth0-collector.template
- collectors/auth0/package.json
- collectors/auth0/test/auth0_mock.js
- collectors/auth0/test/auth0_test.js
- collectors/auth0/test/utils_test.js
- collectors/auth0/utils.js
> Auth0 (Added pagination logic)

- collectors/salesforce/index.js
- collectors/salesforce/package.json
Wrap salesforce in Make handler
> Wrap salesforce in Make handler

- collectors/sophos/collector.js
- collectors/sophos/package.json
- collectors/sophos/themis-template/sophos.json
- collectors/sophos/utils.js
Needed to change some urls and some references to make it work in AWS.
Also some linting errors, going tohave to look at that in the test runner...
Made the required fixes.
> fixes for sophos now that we have a dev environment

- collectors/gsuite/README.md
- collectors/gsuite/cfn/README-GSUITE.md
> G Suite Documentation 

- collectors/googlestackdriver/README.md
The API Key generation instructions needed more descriptive steps
Add more descriptive steps
> update api key instructions to be more descriptive

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/template/package.json.template
Release file cache to the collectors.
> Update paws-collector library in all collectors

- collectors/sophossiem/package.json
- collectors/sophossiem/themis-template/sophossiem.json
> Sophos SIEM themis template issue

- collectors/o365/o365_collector.js
- collectors/o365/package.json
- collectors/o365/test/o365_test.js
> O365 moment state issue

- collectors/carbonblack/themis-template/carbonblackaudit.json
- collectors/carbonblack/themis-template/carbonblackevents.json
Adding themis template validators for the two carbonblack collectors. these will replace the existing themis validator.
> Cb split templates

- collectors/salesforce/collector.js
- collectors/salesforce/package.json
- salesforce attempts unnecessary base64 decoding of collector secret 
- remove base64 decoding
> fix private key decoding

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- collectors/template/package.json.template
- package.json
Needed to update all the collectors to al-aws-collector-js version 3.0.6
> bump collectors to newest al-aws-collector-js version

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- collectors/template/package.json.template
Bump paws library dep to 2.0.0. Which adds ddb sqs deduping functionality.
> bump paws library to 2.0.0

- collectors/o365/healthcheck.js
There was a syntax error that made the o365 tests to fail
fix the syntax error
> fix o365 test

- collectors/sophos/collector.js
- collectors/sophos/local/events/event_poll.json
- collectors/sophos/package.json
- collectors/sophos/test/sophos_test.js
Sophos handled errors for organization type and request limit.
> Sophos handled errors for organization type and request limit.

- collectors/salesforce/collector.js
- collectors/salesforce/local/sam-template.yaml
- collectors/salesforce/package.json
We get below error code without version 48.0 and with version 48 we will get  Log event  received 0 instate of error.
Handle different error code for below events:
> ENG-14517 : Remediation for failing to query inaccessible objects

- collectors/ciscoamp/collector.js
- collectors/ciscoamp/package.json
- collectors/ciscoamp/test/ciscoamp_mock.js
- collectors/ciscoamp/test/ciscoamp_test.js
- collectors/googlestackdriver/collector.js
- collectors/googlestackdriver/package.json
- collectors/googlestackdriver/test/mock.js
- collectors/googlestackdriver/test/test.js
- collectors/gsuite/collector.js
- collectors/gsuite/package.json
- collectors/gsuite/test/gsuite_mock.js
- collectors/gsuite/test/gsuite_test.js
- collectors/salesforce/collector.js
- collectors/salesforce/package.json
- collectors/salesforce/test/salesforce_mock.js
- collectors/salesforce/test/salesforce_test.js
- collectors/sophos/collector.js
- collectors/sophos/package.json
- collectors/sophos/test/sophos_mock.js
- collectors/sophos/test/sophos_test.js
- collectors/sophossiem/collector.js
- collectors/sophossiem/package.json
- collectors/sophossiem/test/sophossiem_mock.js
- collectors/sophossiem/test/sophossiem_test.js
Collectors to report throttling metric
> Collectors to report throttling metric

- package.json
- paws_collector.js
- test/paws_test.js
- Added the method to report client errors on ddMetrics and cloud watch.
-Added the method reportClientOk to  report client execute successfully ,So we can check how often 3rd party APIs get called
> ENG-16247 : Additional collector metrics for client errors

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
To release the  changes of story ENG-18709 with pr (https://github.com/alertlogic/paws-collector/pull/160 )
> ENG-18709 : Bump the version to release the changes of ENG-18709

- collectors/sophos/themis-template/sophos.json
- collectors/sophossiem/themis-template/sophossiem.json
TH ethemis templates done work because the themis api changed
change the templates to conform to the new interface
> change themis templates for new themis params

- collectors/salesforce/collector.js
- collectors/salesforce/package.json
- collectors/sophossiem/collector.js
- collectors/sophossiem/package.json
Removed the custom message as we are getting **errorCode:Unknown** in DD metric on client metric.
> ENG-0000 :Removed custom message for salesforce  and sophossiem errors

- package.json
Bump paws-collector version in package.json.
> Bump paws-collector version

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- collectors/template/package.json.template
Need to bump versions to pick up new `paws-collector` changes.
Bump the dependency version in all collectors.
> Bump paws-collector package version in all collectors

- collectors/o365/local/sam-template.yaml
- collectors/o365/o365_collector.js
- collectors/o365/package.json
Review remediaitons and status updates for O365 collectors and add new remediations where necessary
> [paws-collector] Review collector remediations / status for O365

- collectors/auth0/auth0_collector.js
- collectors/auth0/package.json
- collectors/carbonblack/collector.js
- collectors/carbonblack/package.json
- collectors/ciscoamp/collector.js
- collectors/ciscoamp/package.json
- collectors/ciscoduo/collector.js
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/collector.js
- collectors/googlestackdriver/package.json
- collectors/gsuite/collector.js
- collectors/gsuite/package.json
- collectors/o365/o365_collector.js
- collectors/o365/package.json
- collectors/okta/okta_collector.js
- collectors/okta/package.json
- collectors/salesforce/collector.js
- collectors/salesforce/package.json
- collectors/sentinelone/collector.js
- collectors/sentinelone/package.json
- collectors/sophos/collector.js
- collectors/sophos/package.json
- collectors/sophossiem/collector.js
- collectors/sophossiem/package.json
While sending the log msgs ,the application id should be in camelcase as mention in [common_proto.piqi_pb.js](https://github.com/alertlogic/al-collector-js/blob/npm/proto/common_proto.piqi_pb.js#L1050) other wise it will not set the applicationId value while sending to ingest
Updated application_id to applicationId.
> Corrected applicationId while formating the logs and sending to ingest

- collectors/o365/o365_collector.js
- collectors/o365/package.json
- collectors/o365/test/o365_test.js
Getting the MS management api below errors:
1. Maximum payload size exceeded
2. Content older than 7 days cannot be retrieved ;when we make call for each ContentUri in ayncPool. 
ex : `Content requested with the key 20210630122427504000475$20210630122427504000475$audit_sharepoint$Audit_SharePoint$na0047 has already expired. Content older than 7 days cannot be retrieved`.
1. Reduce the time duration by 2 ;If duration is 1hr then we set to state.until to 30min.
2. Change the PARTIAL_WEEK to PARTIAL_WEEK_HOURS and set the 6 days 23hr to avoid the error `Content older than 7 while making call to each contentUri.
> Handle the MS management api issues

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/o365_collector.js
- collectors/o365/package.json
- collectors/o365/test/o365_test.js
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
1. Duplicate state issue
2. Max payload issue
Fixed both issues in below PR's
1. Refresh state([pr](https://github.com/alertlogic/paws-collector/pull/194))
2. Handle the Max payload error([pr](https://github.com/alertlogic/paws-collector/pull/195))
> Bump the all collector version to fix the duplicate state and max payload Issue

- package.json
- paws_collector.js
Catch exception and fail the invocation without status update.
> Catch errors in handlePollRequest

- collectors/mimecast/package.json
- collectors/mimecast/utils.js
Exception is happening in asynchronous function hence no catch in `Promise.catch()`
Catch parsing exception inside asynchronous function and reject promise.
> Catch JSON parse exceptions

- collectors/mimecast/package.json
- collectors/mimecast/utils.js
Response body is not visible in parsing exception
Add log message
> Mimecast. Output body failed to be parsed

- collectors/mimecast/package.json
- collectors/mimecast/utils.js
Collector failed parsing 5XXs response bodies
Reject promise in case of 5XXs
> [Mimecast] Handle 500s

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
Processing the logs in batch if log size >10K.
> Bump the version of all paws collector for processing logs in batch

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
Reduce the fluctuations rate of collector status [pr](https://github.com/alertlogic/paws-collector/pull/210)
> Bump the all paws collector version to reduce the fluctuations rate of collector status

- collectors/crowdstrike/collector.js
- collectors/crowdstrike/package.json
Changed polling interval from n-cap to hour-cap as per suggestion
> Changed polling interval from n-cap to hour-cap as per suggestion

- collectors/crowdstrike/cfn/README.md
Added crowdstrike readme for collector template
> Added README for collector template

- collectors/auth0/auth0_collector.js
- collectors/auth0/package.json
- collectors/auth0/test/auth0_test.js
- collectors/auth0/utils.js
IF last log id is null then it start from current moment instate of last collected time stamp.
In initial call if we get nextLogId  null then set last collected time stamp and if last collect time is undefined then start with current time.
> AuthO : In case if nextLogId is null then set the state on basic of last collected Ts 

- collectors/crowdstrike/package.json
- collectors/crowdstrike/utils.js
Changes for adding user-agent in the HEADER of calls
> Changes for adding user-agent in the HEADER of calls

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/crowdstrike/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
Reference  pr https://github.com/alertlogic/paws-collector/pull/227 .
> Bump the collector version for assets status

- cfn/paws-collector-shared.template
- cfn/paws-collector.template
> Use arm64 arch for lambda functions

- collectors/okta/README-OKTA.md
- collectors/okta/okta_collector.js
- collectors/okta/package.json
- collectors/okta/test/okta_test.js
No error code was not handle
Added an error code using which datadog can represent that error code in the graph.
> change to handle no error code

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/crowdstrike/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
All paws deployment failed as updateFunctionConfiguration calls may fail if Lambda status is InProgress.
Fix in al-aws-collector-js lib and then in paws lib .[pr](https://github.com/alertlogic/paws-collector/pull/237)
> [All paws collector ]Bump the package to fix Lambda.updateFunctionConfiguration failures

- collectors/o365/package.json
Reference pr - [pr1](https://github.com/alertlogic/paws-collector/pull/239) [pr2](https://github.com/alertlogic/paws-collector/pull/241)
> 0365 : SSM value should stored and read in correct encoding file format

- package.json
- paws_collector.js
AWS cost is increase due to lots of logs get ingested in cloud watch.
Improve the logging functionality with Winston logger.
> PAWS Lib : Improve the logging functionality with Winston logger

- collectors/googlestackdriver/collector.js
- collectors/googlestackdriver/package.json
- collectors/googlestackdriver/test/test.js
Throttling error with message size greater than expected. Below is the error message :
`Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4518352 vs. 4194304)`
In case of error, half the time stamp interval and try again until the 15sec. If error still exist then skip or move the interval window by 15 sec.
> [Googlestackdriver Collector]Handle the RESOURCE_EXHAUSTED  error with message size greater than expected

- cfn/paws-collector-shared.template
- cfn/paws-collector.template
- package.json
- paws_collector.js
- ps_spec.yml
To upgrade paws collector node js version
Updated paws collector to node 14 and also bumped the package version
> Paws collector node 14 update

- collectors/crowdstrike/al-crowdstrike-collector.json
- collectors/crowdstrike/local/sam-template.yaml
- collectors/crowdstrike/package.json
Crowdstrike support for node 14
Upgraded Crowdstrike runtime and sam local node version and bumped package version.
> Crowdstrike collector node 14 changes

- collectors/okta/README.md
- collectors/okta/al-okta-collector.json
- collectors/okta/local/run-sam.sh
- collectors/okta/local/sam-template.yaml
- collectors/okta/package.json
Okta collector node version update
Changes regarding okta collector node version update and change in package version.
> Okta node 14 update

- collectors/o365/al-o365-collector.json
- collectors/o365/local/run-sam.sh
- collectors/o365/local/sam-template.yaml
- collectors/o365/package.json
Upgrade O365 to node 14
Made node 14 changes and also bumped the package
> Changes for o365 node 14 update

- cfn/paws-collector-shared.template
- cfn/paws-collector.template
- ps_spec.yml
…changes pushed to prod and validating
Revert paws collector core changes till all collectors tested
Reverting paws collector node 14 updates till all collectors node 14 changes testing on prod
> Reverting paws collector node 14 updates

- package.json
Update dependences to support shared SNS triggers for checkins and updates.
> Shared SNS triggers

- collectors/ciscoamp/al-ciscoamp-collector.json
- collectors/ciscoamp/local/sam-template.yaml
- collectors/ciscoamp/package.json
- local/run-sam.sh
Ciscoamp Node V14 Update.
- Updated paws collector version in package json.
- Updated runtime in ciscoamp collector.
- Added missing fields in sam-template.
- Updated node version in sam-template.
- Updated run-sm Script with Profile.
> Changes for ciscoamp node Version 14 update

- collectors/okta/package.json
Follow up change for https://github.com/alertlogic/paws-collector/pull/260 with fixed function updates.
> [Okta] Add shared SNS trigger support. Fixed updates

- cfn/paws-collector-shared.template
Update collectors CFN to use shared update and checkin triggers via SNS.
> [WIP] Update CFN with shared SNS triggers.

- collectors/crowdstrike/local/run-sam.sh
- collectors/sentinelone/al-sentinelone-collector.json
- collectors/sentinelone/local/sam-template.yaml
- collectors/sentinelone/package.json
Sentinel one collector update to node 14
Changes for sentinel one collector update to node 14
> Changes for sentinel one node 14 update

- cfn/paws-collector-shared.template
- cfn/paws-collector.template
- collectors/template/collector.json
- collectors/template/local/sam-template.yaml
- local/sam-template.yaml
Upgrade main paws collector to node 14
Changes to support paws collector upgarde to node 14
> Paws node 14 update

- collectors/mimecast/collector.js
- collectors/mimecast/package.json
- collectors/mimecast/utils.js
No debug logs in mimecast collector
Added debug logs in mimecast collector
> Added some debug logs in mimecast collector

- collectors/mimecast/utils.js
mimecast debug log 
fixed debug format
> mimecast debug log changes

- collectors/mimecast/package.json
update package version
updated package version mimecast
> updating mimecast version in package.json

- collectors/mimecast/package.json
- collectors/mimecast/utils.js
add logs and update package.json
mimecast added logs and update package.json version
> Mimecast debug logs changes

- collectors/mimecast/cfn/mimecast-collector.template
update PawsMaxPagesPerInvocation to 5 in mimecast
updated PawsMaxPagesPerInvocation to 5 in mimecast
> PawsMaxPagesPerInvocation updated in mimecast cfn

- collectors/ciscoamp/collector.js
- collectors/ciscoamp/package.json
- collectors/ciscoamp/test/ciscoamp_test.js
Collector try to pull the data for one month interval and showing throttling error continuously .Throttling error not  resolved after couple of time tried .
`CAMP000001 Collecting data for Events from 2022-07-01T10:46:51.950Z till 2022-07-31T18:18:28.542Z`
`CAMP000003 API hourly Limit Exceeded. The quota will be reset at 2022-08-11T07:42:19.690Z"`
Used the day cap if start time is greater than 24 hr and reduce the time interval and try to fetch if not then reduce the time interval again till 60 sec.
> [Cisco AMP]: Handle throttling error

- .github/workflows/code-coverage.yml
- .gitignore
- .npmignore
- Makefile
- collectors/collector.mk
- package.json
- ps_spec.yml
Problem Description
add code coverage report for paws-collector
Solution Description
added code coverage report for paws-collector
> add test coverage report for paws-collector

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/crowdstrike/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- collectors/template/package.json.template
- ps_spec.yml
bump paws-collector package version in all collectors
bumped paws-collector package version in all collectors
> [All paws collectors] bump paws-collector package version in all collectors

- ps_spec.yml
update ps_spec  to skip if git tag already exists
ps_spec updated to skip if git tag already exists
> updated ps_spec  to skip if git tag already exists

- .github/workflows/code-coverage.yml
- package.json
Problem Description
AWS inspector Findings: By Lambda function reported cve vulnerabilites in npm packages
Solution Description
Fixed AWS inspector Findings: By Lambda function reported cve vulnerabilites in npm packages
> NPM vulnerabilities in paws-collector fixes

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/crowdstrike/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/gsuite/test/utils_test.js
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- collectors/template/package.json.template
Problem Description
AWS inspector Findings: By Lambda function reported cve vulnerabilites in npm packages
Solution Description
Fixed AWS inspector Findings: By Lambda function reported cve vulnerabilites in npm packages
> NPM Vulnerabilities fixes and package.json update in collectors

- collectors/gsuite/cfn/README-GSUITE.md
- collectors/gsuite/cfn/gsuite-collector.template
- collectors/gsuite/local/run-sam.sh
- collectors/gsuite/package.json
- collectors/gsuite/test/gsuite_test.js
Add context_aware_access and chrome in Gsuite Application Names
Added context_aware_access and chrome in Gsuite Application Names
> Added context_aware_access and chrome in Gsuite Application Names

- cfn/paws-collector-shared.template
- package.json
- paws_collector.js
- test/paws_mock.js
- test/paws_test.js
O365 management api return the same message multiple time which result in duplicate incident . 
Storing the logs for 24 hr and checking if the message is already exist return the exception else add to ddb table.
Once all  duplicate message is removed then send to ingest service.
> Handle the duplicate item issue by adding item in ddb conditionally

- collectors/o365/o365_collector.js
- collectors/o365/package.json
- collectors/o365/test/o365_mock.js
- collectors/o365/test/o365_test.js
The updating the collect lambda Iam policy for not shared role . This will allow to write the data in deduplication table now.
> [o365- collector]: Release the change to handle the duplicate log for o365 management api

- collectors/gsuite/README.md
- collectors/gsuite/cfn/README-GSUITE.md
- collectors/gsuite/package.json
Gsuite Collector update readme with context aware and alerts feature setup details
Gsuite Collector updated readme with context aware and alerts feature setup details
https://alertlogic.atlassian.net/browse/ENG-50853
> [Paws-Gsuite] updated readme with context aware and alerts feature setup details

- collectors/mimecast/collector.js
- collectors/mimecast/package.json
- collectors/mimecast/test/mimecast_test.js
- collectors/mimecast/test/utils_test.js
- collectors/mimecast/utils.js
- collectors/salesforce/package.json
1. Fix the vulnerabilities related to request package for mimecast
2. Bump the salesforce package missed in last  [pr](https://github.com/alertlogic/paws-collector/pull/344/files#diff-8e2fe486da232865ad490e3e034fa0da6a9b0e62c870b3bb4a56571610ec88c3L3)
> [ENG-50123]: Fix the vulnerabilities related to request package for mimecast

- collectors/mimecast/collector.js
- collectors/mimecast/package.json
- collectors/mimecast/test/mimecast_test.js
- collectors/mimecast/test/utils_test.js
checking response.status value instated of status from meta object as it will not available in few error format.
> [ENG-50123 : Mimecast ]: Update throttle handle error status format 

- collectors/sophossiem/collector.js
- collectors/sophossiem/package.json
What was fixed? - root cause
for error 401 there is no error object return from api so returning custom error message instated of null
> [sophosiem] :Bump the version to fix the sophosiem error format

- collectors/auth0/package.json
- collectors/auth0/test/auth0_test.js
- collectors/carbonblack/package.json
- collectors/carbonblack/test/Carbonblack_test.js
- collectors/ciscoamp/package.json
- collectors/ciscoamp/test/ciscoamp_test.js
- collectors/ciscoduo/package.json
- collectors/ciscoduo/test/ciscoduo_test.js
- collectors/crowdstrike/package.json
- collectors/crowdstrike/test/crowd-strike-test.js
- collectors/googlestackdriver/package.json
- collectors/googlestackdriver/test/test.js
- collectors/gsuite/package.json
- collectors/gsuite/test/gsuite_test.js
- collectors/mimecast/package.json
- collectors/mimecast/test/mimecast_test.js
- collectors/o365/package.json
- collectors/o365/test/o365_test.js
- collectors/okta/package.json
- collectors/okta/test/okta_test.js
- collectors/salesforce/package.json
- collectors/salesforce/test/salesforce_test.js
- collectors/sentinelone/package.json
- collectors/sentinelone/test/sentinelone_test.js
- collectors/sophos/package.json
- collectors/sophos/test/sophos_test.js
- collectors/sophossiem/package.json
- collectors/sophossiem/test/sophossiem_test.js
Lambda Runtime nodejs 18 used aws-sdk v3 version.
Upgrade aws-sdk v2 to v3 and fixed the functionality if anything change as per v3 version.
> ENG-51681 : Upgrade all collectors aws-sdk version from v2 to v3 and rewrite functionality and testcases

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/crowdstrike/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
Failed the build as  unit test cases failed -https://ui.pipelineservices.alertlogic.com/builds/defender/paws-collectors-deploy-pipeline/564
Added required dev dependancy in all collector to run the test cases successfully.
> ENG-51681[Migrate aws-sdk v2 to v3] : Added missing dev dependancy to run test cases

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/crowdstrike/package.json
- collectors/googlestackdriver/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
Bump all collectors version to handle the max payload issue.
> Bump the collector to handle the max payload issue

- Makefile
- README.md
- build_collector.sh
- ps_spec.yml
[ENG-53643]Collector release cycle improvements[Build CI job and CD job]
Create the CI job which build the artifact based on tag version when pr got merged or on trigger the phrase.
1. Added the 14 stage to build the package and upload to artifact storage for individual collectors.
2. Added the one more stage which will create the single artifact including all collectors whenever the tag get created.
> [ENG-53643]Collector release cycle improvements[Build CI job and CD job]

- ps_spec.yml
bump googletstackdriver collector version to 1.2.9 in ps_spec
> bump googletstackdriver collector version to 1.2.9 in ps_spec

- .github/workflows/code-coverage.yml
- cfn/paws-collector-shared.template
- cfn/paws-collector.template
- package.json
- ps_spec.yml
Node.js 20.x runtime now available in AWS Lambda
Upgrade  the lambda runtime nodejs version from 18 to 20
> [ENG-55635]: Upgrade  the lambda runtime nodejs version from 18 to 20

- package.json
- ps_spec.yml
Currently not publishing the Paws lib because the code got removed [pr](https://github.com/alertlogic/paws-collector/pull/362/files#diff-fe2d2167c48c5f25fe339faa2b3f503af5d9f0047ab487bf358c4044addfd3cdL25)
Fix the code to publish the lib
> Publish the lib while merge to master if version get upgrated

- collectors/ciscomeraki/collector.js
- collectors/ciscomeraki/package.json
- ps_spec.yml
Issue when selfupdate triggered networks json is not created in s3 bucket
How it was fixed? - implementation details
Condition check issue change field networksFromS3.code to networksFromS3.Code in if condition to create s3 bucket
> [Cisco Meraki Collector] Integration testing small fix creation of bucket in s3 when self update

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/ciscomeraki/package.json
- collectors/crowdstrike/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- ps_spec.yml
Bumped paws lib version, al-aws-collectorjs in all collectors.
> [All Collectors]:  Bumped paws lib version, al-aws-collectorjs in all collectors

- collectors/auth0/package.json
- collectors/carbonblack/package.json
- collectors/ciscoamp/package.json
- collectors/ciscoduo/package.json
- collectors/ciscomeraki/package.json
- collectors/crowdstrike/package.json
- collectors/gsuite/package.json
- collectors/mimecast/package.json
- collectors/o365/package.json
- collectors/okta/package.json
- collectors/salesforce/package.json
- collectors/sentinelone/package.json
- collectors/sophos/package.json
- collectors/sophossiem/package.json
- ps_spec.yml
Bumped sinonjs and collectors version
> [All Collectors]: Bumped sinonjs and collectors version

- package.json
Find the vulnerability by AWS inspector
Update the Dependancy due to which below vulnerability are found :
CVE-2024-21538
CVE-2024-57965
CVE-2025-27152
CVE-2025-27789
> [ENG-57847-Paws lib]Fix the vulnerability find by aws inspector
