alertlogic/paws-collector

cfn/okta-collector.template, collectors/okta/package.json, package.json, paws_collector.js
PAWS mistakenly overriden `_collectorType` property of the base class.
Use `paws._pawsCollectorType` instead.
Make okta template parameters friendly.
=> Fix paws collector registration

cfn/auth0-collector.template, cfn/okta-collector.template
Collector get permission error  for `DescribeStacks` because of resource constraint.
Use `*` resource for `DescribeStacks`
=> Add DescribeStack action

cfn/paws-collector.template, package.json, paws_collector.js, test/paws_mock.js, test/paws_test.js
Add a common template. Ideally a collector template will proxy input parameters and have only one 
AWS::CloudFormation::Stack resource.
Also PAWS secret parameter encryption was added, same way AIMs secret is encrypted.
=> Common template with PAWS secret encryption

collectors/auth0/auth0_collector.js, collectors/auth0/cli.js, collectors/auth0/package.json, package.json
Unnecessary effort is required to simply test that the collection implementation in a paws collector works.
Provide a simple command-line driver that will exercise the collection aspect of a collector independent of any Alert Logic identity, registration, transport, etc.
This is not a substitute for automated tests but it will confirm that the collector implementation actually collects logs.
I suggest we integrate this into the collector template/generator also (separate PR).
Compared to #22 -
* Updated for changes in paws framework
* Fix auth0 clientId
To run this (**please note argument changes**):
```
cd collectors/auth0
npm install
node cli.js --paws_endpoint=$DOMAIN --paws_api_client_id=$CLIENT_ID --paws_api_secret=$CLIENT_SECRET
```
=> Implement CLI driver for auth0

package.json, paws_collector.js, test/paws_test.js
Allow multiple collection states in order to increase performance.
Note, up to 10 collection states can be returned for now. Refer to TODO.
=> Allow collectors return multiple collection states

cfn/collector.template.template, cfn/o365-collector.template, cfn/paws-collector.template
`cloudformation:DescribeStacks` only supports `*` resource
Fix `DescribeStacks` permission
=> Fix checkin permissions

cfn/o365-collector.template
Poll endpoint is constant for all o365 collectors. Therefore there is no need to have it as an input parameter in CFN.
=> Use constant paws_endpoint for o365

collectors/okta/okta_collector.js, collectors/okta/package.json, collectors/okta/test/okta_test.js
Make okta collector report 429 rate exceeded errors.
Unfortunately okta SDK doesn't include any codes into errors, only test messages.
=> Okta: Report throttling errors

.travis.yml, collectors/auth0/auth0_collector.js, collectors/auth0/package.json, collectors/googlestackdriver/collector.js, collectors/googlestackdriver/package.json, collectors/gsuite/collector.js, collectors/gsuite/package.json, collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/okta/okta_collector.js, collectors/okta/package.json, index.js, package.json, paws_collector.js, paws_utils.js
Collection interval-related calculations are duplicated across all collectors.
New function has been added in paws_collector library: `calcNextCollectionInterval`
- strategy: can be one from the list
1. `'no-cap'` - do not cap collection interval length
2. `'day-cap'` - limit collection interval length to day
3. `'hour-cap'` - limit collection interval length to hour
4. `'hour-day-progression`' - if collection interval is longer than day limit it to one day, if it shorter than day but longer than hour limit it to one hour
5. `'day-week-progression`' - if collection interval is longer than week limit it to one week, if it shorter than week but longer than day limit it to one day
- `curUntilMoment` - current until moment() from collection state
- `pollInterval` - current polling interval …
=> add function to calculate collection interval to the library

package.json, paws_collector.js, test/paws_test.js
- SQS batch size is limited to 10 messages per batch
- split batches into slices of >10 and submit concurrently to AWS
=> Collector state batch splitting

cfn/paws-collector.template
- missing comma in paws-template cfn
- add comma
=> fix paws_template syntax

collectors/o365/test/o365_mock.js
there was a param name missing from the test mocks. Looks like i didnt commit it last time
added the param in. though it is for the collect aws account. you may need to change for you test account.
=> add param name to test mock

collectors/okta/okta_collector.js, collectors/okta/test/okta_mock.js, collectors/okta/test/okta_test.js
- Okta publish sensitive apiToken information in log objects 
- Remove this field from the object for the time being
=> remove apiToken from log object

collectors/okta/health_checks.js, collectors/okta/okta_collector.js, collectors/okta/package.json, collectors/okta/test/okta_test.js, package.json, paws_collector.js
needed a health check to monitor status of okta collector
add a healthcheck, calling the /me endpoint of the okta API manually as this method isn't implemented by the SDK
=> token healthcheck for okta

collectors/collector.mk
We still should see `stderr` output in case of any issues.
=> Skip stdout for packages

collectors/carbonblack/cfn/carbonblack-collector.template
Organisation key should be optional, as it's only required to ping the CarbonBlack Alerts API.
Also, some descriptions of fields reference OAuth2 authentication, which is not used by CarbonBlack.
Add a default value for organisation key.
Update field descriptions.
=> make org key optional + description fixes

collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/o365/test/o365_test.js
o365 just errors if a state has gotten more than 7 days old.
if the collector gets a state more than 7 days old, collect the last logs.
=> update old states to collect last logs

collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/o365/test/o365_test.js
There was an issue with time rounding in the last fix. by default, moment truncates time diffs rather than rounds up.
there was also an issue where, even if the collector was updating the state, it would try the next page token anyway, causing an error.
force moment to give time ranges as a float
remove nextpage url if the state is out of date.
=> Fix time rounding an next page token issue

package.json, paws_collector.js
update to the latest `al-aws-collector-js`. The `application_id` getter was moved there.
=> Update al-aws-collector dependency

collectors/okta/okta_collector.js, collectors/okta/package.json
Customers can input urls without `https` prefix.
Stop using `process.env` and use `pawsHttpsEndpoint` property.
=> Always use HTTPS endpoint

collectors/o365/README.md
Duplicated the legacy Office 365 information from
https://docs.alertlogic.com/configure/office365-new-log-collector.htm
=> O365 README: add link to old collector set up instructions

collectors/o365/README.md
Azure has deprecated a few of their permissions, namely `ThreatIntelligence.Read` and `ActivityReports.Read`. They have been wrapped into the remaining permissions
Remove references to the deprecated permissions in the ReadMe
=> update permission set for o365 collectors

collectors/carbonblack/README.md
Some confusion around which url was required for the CarbonBlack collector
Add a table of URLs in API credentials setup section of ReadMe
=> update carbonblack readme with api urls

package.json, paws_collector.js, test/paws_test.js
There was no cache for param store credentials. this was causing us to hit AWS rate limits.
Added a file cache to the param store call. This should reduce the number of calls to AWS SSM.
=> Add file cache for param store value

collectors/sentinelone/collector.js, collectors/sentinelone/package.json
Sentinelone was configured to have the "no cap" progression for catching up with historical logs, which was not very efficient.
changed it to "day hour" progression.
=> change progression on next state function

package.json
- Collection periodically fails due to unlink of cache throwing a ENOENT error: https://github.com/alertlogic/al-collector-js/pull/42
- Update al-aws-collector dependency to include fix
=> update al-aws-collector dependency with unlink file fix

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json, collectors/template/package.json.template
- collectors may crash when trying to unlink non existent cache file
- update paws dependency to version that fixes this
=> bump paws dependency

collectors/o365/o365_collector.js, collectors/o365/package.json
- When collecting a large number of objects, we hit the OS socket limit due to large number of parallel calls to o365 api's
- limit concurrent api calls to 20
=> Limit concurrent calls to o365 Management API 

collectors/okta/package.json, collectors/sentinelone/package.json
Forgot to bump package versions in the previous PR, removing the S1 and Okta healthchecks
Remedy the situation and bump the versions
=> bump package versions for okta and s1

cfn/paws-collector.template, paws_collector.js
SSM Parameter Store has a size limit of 4KB for `Standard` tier parameters. This causes problems for the Salesforce collector where the secret is an RSA private key -- after encryption in KMS and base64 encoding, the size of the resulting parameter exceeds the 4KB limit.
The paws-collector template is updated to use `Intelligent-Tiering` by default, so that `Advanced` tier parameters are created when the parameter's size exceeds 4KB.  `Standard` tier parameters are created otherwise.
=> Use Intelligent-Tiering for storing parameters in SSM

package.json, paws_collector.js
Existing collectors won't have `paws_secret_param_tier` exposed in env vars which would cause parameter updates to fail when SSM set-parameter request is sent with `Tier=undefined`.
Default to `Standard` tier when `paws_secret_param_tier` is not defined in environment variables since this likely means the stack is using an old template version and so its parameters will have been created with the `Standard` tier initially anyway.
=> Default to SSM Standard tier where tier is undefined in env

collectors/ciscoduo/package.json
I did not use the `update-collector-versions.js` script to update the collector versions and subsequently missed a collector.
Bump dependency + package version in the missed collector.
=> Bump paws-collector dep in ciscoduo collector

collectors/auth0/package.json, collectors/auth0/utils.js
- cases where customers have used valid date times such as `2021-02-16T21:46:54Z` (missing millisecond time)
- auth0 throws error when attempting to call apis without milliseconds timestamp
- convert such datetime strings into valid ISO8601 format
=> convert collection_start_ts to ISO8601

cfn/paws-collector.template, package.json, paws_collector.js
1.Passed the streams array to al-aws-collector to post ok status in checkin event
2.Send the stream from done function to post the error  status specific to stream.
3. Added collectorType parameter in prepareErrorStatus to override the prepareErrorStatus of al-aws-collector when there is stream specific error status.
Prerequisite:
[al-aws-collector/62](https://github.com/alertlogic/al-aws-collector-js/pull/62)
=> ENG-17586 :  [paws-collectors] Stream specific status reporting 

cfn/paws-collector.template, package.json, paws_collector.js
The size of the key is grater than 4kb , when encrypted and encoded as base64, is too large to be stored in the CustomResource before being stored in SSM .
Instead  encrypting the paws secret using EncryptLambdaFunction, we should store the secret directly in **SSM Parameter Store as a SecureString**. Create SSM  SecureString parameter with the help of Lambda function instate of CFN template (as 
mentioned on AWS doc - `SecureString is not currently supported for AWS CloudFormation templates`.) .
1. Added Lambda Function (CreateSsmParameterLambdaFunction ) which will create the SSM parameter with Secure String and return the Parameter name and version.If `event.RequestType == 'Delete'` then Delete the SSM parameter.
2. Modified the  EncryptLambdaPolicy to allow (ssm:PutParameter) which …
=> VTT-2603: Create SSM secure parameter by Lambda function

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
The size of the key is grater than 4kb , when encrypted and encoded as base64, is too large to be stored in the CustomResource before being stored in SSM .
Fixed the issue in [paws-180-pr](https://github.com/alertlogic/paws-collector/pull/180)
=> VTT-2603 : Updated paws version to create SSM param  by lambda function

collectors/sophossiem/package.json, collectors/sophossiem/test/sophossiem_test.js, collectors/sophossiem/test/utils_test.js, collectors/sophossiem/utils.js
Sophosiem  collector showing the as unhealthy/not receiving logs within the last 24hours.
The undefined is getting appended instated of api url as objectName was not available in state object and so getting error code 403 from below api request.
https://api5.central.sophos.com/gatewayundefined?from_date=&limit=1000
Used stream from state object and remove objectName which no longer available in state object.
=> Fixed the SophoSIEM  stream issue

collectors/sophossiem/collector.js, collectors/sophossiem/package.json
Sophos api retuning `INVALID_REQUEST` as from date grater than 24 hr. 
https://api3.central.sophos.com/gateway/siem/v1/events?from_date=1616582131&limit=1000
Check if date is grater than 24 hr set new date which is within 24 hr in state object.
=> Sophos : Fixed the invalid request issue

collectors/sophos/collector.js, collectors/sophos/local/sam-template.yaml, collectors/sophos/package.json, collectors/sophos/test/sophos_test.js
Sophos collector should show same error message on UI which we can see in cloud watch logs.
For below customer it showing error  `Alert Logic collector Sophos-Group hasn't sent logs to Alert Logic for the past 24 hours.' on UI, But actually it getting below error message on cloud watch logs
Customer Id :68582699 
Region : eu-west-1
Collector : Sophos
Collector Id :F31E634F-68D7-42FF-B55B-90CDFF109236
Error message : "Please generate credentials for the tenant. Currently we do not support credentials for Organization and Partner.
I have tested this error message and it's showing on remediations page. Also added new remediations for invalid credentials.
=> [paws-collector] Review collector remediations / status for Sophos

package.json, test/paws_test.js
After lmcstats changes timeout issue get introduce and to fix that updated the al-aws-collector-js version to [4.0.2](https://github.com/alertlogic/al-aws-collector-js/pull/66).
Also reverted  the  test case changes added in last [pr](https://github.com/alertlogic/paws-collector/pull/185/files) .
=> ENG-25186: Bump the paws collector version to fix time out issue.

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
Updating the al-aws-collector and paws-collector version to fix time out issue which is introduce in lmcstats changes. al-aws-collector [version](https://github.com/alertlogic/al-aws-collector-js/pull/66)
=> ENG-25186 :Bump the paws and al-aws-collector version to fix timeout issue

collectors/carbonblack/README.md, collectors/carbonblack/local/env.json.tmpl, collectors/carbonblack/package.json, collectors/carbonblack/test/Carbonblack_test.js, collectors/carbonblack/test/carbonblack_mock.js, collectors/carbonblack/utils.js
Getting 404-undefined error for CB vmware search stream for below api .
`<cbc-hostname>/appservices/v6/orgs/${orgKey}/alerts/vmware/_search`. [CB search alert  api document](https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/alerts-api/#api-calls) not supporting this api.
Remove Search_Alerts_Vmware stream from api_names. So , now it pull data for rest of 3 streams.
Also removed stream from catlog.json of [Applications pr](https://algithub.pd.alertlogic.net/defender/applications/pull/133).
=> ENG-26751 : Removed the SearchAlertsVmware stream from CB as alert api not supported

collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/o365/test/o365_test.js
For few collectors , it was observed that the collector takes so long to handle the huge paged response from MS Management API when collector state.since timestamp stored in SQS becomes older than 7 days ; in this case ,we reset the state and get the [1hr](https://github.com/alertlogic/paws-collector/blob/master/collectors/o365/o365_collector.js#L106) data but when it goes for [nextCollection](https://github.com/alertlogic/paws-collector/blob/master/collectors/o365/o365_collector.js#L164) and now the pull time duration is 24hr as we are using `hour-day-progression` to calculate the next duration.  Below are the listed cases which reporting issues :
- Case 1.  Time :5min and Memory : 256 MB
The data is so huge for 24hr duration ,so we get `Task time out ` from lambda.
- Case 2. By …
=> VTT-3058 : Change the hour-day-progression to hour_cap to handle the huge paged response

package.json, paws_collector.js, test/paws_test.js
Error state messages are expired in SQS due to retention period.
Failed invocations are not retried because wrong DDB state handling.
Refresh SQS state message every invocation even if poll request for logs failed.
Add new DDB record state `FAILED` in order to retry failed invocations instead of treating them as duplicates.
=> Refresh state

collectors/sentinelone/README.md, collectors/sentinelone/package.json, collectors/sentinelone/utils.js
SentinelOne api minor version changed, 2.0 no longer supported (seemingly)
Change api endpoint in `getAPILogs` for SentinelOne to the new 2.1 version
=> update sentinelone endpoint, remove docs from readme

package.json, paws_collector.js, test/paws_test.js
For O365 collector when we pulling the data for 1hr duration, if data size > 10Mb then al-collector.js  [buildPayload](https://github.com/alertlogic/al-collector-js/blob/master/al_log.js#L97) method return Max payload issue.
Reduce the pull interval by 2 and accordingly updated the state value
=> Changes to handle the Max payload error

collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/o365/test/o365_test.js
For few o365 collectors getting issue while collecting the data for 1hr interval as data is huge(>10Mb);
ex: lambdaError: Runtime exited with error: signal: killed; even we set memory to 2048 and time to 15 min 
Adjust the collection interval if paws_collection_interval variable exist in environment variables
=> Adjust the collection interval for o365 

paws_collector.js, test/paws_test.js
For few o365 collector we found ingest error, max payload issue and other issues if data is huge . So process logs in batches.
Split the data per 10K message size and create batch. Call the processLog to send Logmsgs to ingest.
=> Process the logmsgs in batch if log messages size greater than 10K

package.json, paws_collector.js, test/paws_test.js
If there is intermediate  errors then collector status fluctuating from healthy to unhealthy and vice versa
Added the retry_count in SQS state and increment the value if error occurred . If retry_count reached to 5 then only send the error status to assets to reduce the fluctuations of collector status.
=>  Reduce the fluctuations rate of collector status

package.json, paws_collector.js, paws_health_checks.js, test/paws_health_test.js
Checkin function update the status to ok if there is no error on Lambda Error metrics.
Paws collector not sending error to Lambda error metrics in few scenario ;so Checkin function update the status to 'ok' even we have error for collector. But paws collector send the error to custom metrics like [PawsClientError](https://github.com/alertlogic/paws-collector/blob/master/paws_collector.js#L414)/[PawsIngestError](https://github.com/alertlogic/paws-collector/blob/master/paws_collector.js#L537) .
Fetch the data from `PawsClientError` metrics using getCustomMetrics and send as health check to [al-aws-collector.js](https://github.com/alertlogic/al-aws-collector-js/blob/master/al_aws_collector.js#L128) which will check the status in [ checkin function …
=> Added the custom health check for Paws collector

cfn/paws-collector.template, package.json, paws_utils.js
Few  Paws collector missed the data.This issue we seen for Cisco duo collector.
Scenario : When we made the api call just within the 1 min( at 7.43.59 pm we try to fetch the data for duration of 7.41.27pm to 7.42.27pm.)  
There may be chance of complete data was not available at that time when we make api call within a min.
Make the api call for the time stamp of 10 to 15 min ago.
Set the NEXT_POLL_INTERVAL_DELAY to 10 to 15 min If current time and nextUntilMoment difference is less the NEXT_POLL_INTERVAL_DELAY seconds.
=> Added Poll interval delay for paws collector

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/carbonblack/test/Carbonblack_test.js, collectors/ciscoamp/package.json, collectors/ciscoamp/test/ciscoamp_test.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_mock.js, collectors/ciscoduo/test/ciscoduo_test.js, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/test.js, collectors/gsuite/package.json, collectors/gsuite/test/gsuite_test.js, collectors/mimecast/package.json, collectors/mimecast/test/mimecast_test.js, collectors/o365/package.json, collectors/o365/test/o365_mock.js, collectors/o365/test/o365_test.js, collectors/okta/package.json, collectors/okta/test/okta_test.js, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sentinelone/test/sentinelone_mock.js, collectors/sentinelone/test/sentinelone_test.js, collectors/sophos/package.json, collectors/sophos/test/sophos_mock.js, collectors/sophos/test/sophos_test.js, collectors/sophossiem/package.json
- Bump the PAWS collectors version to add the custom health check for those  collector which does not having it own health check .[pr](https://github.com/alertlogic/paws-collector/pull/213) 
- Added the poll interval delay while calculating NextCollectionInterval if collector collecting data within last 10 min interval [pr](https://github.com/alertlogic/paws-collector/pull/216).
=> Bump the all collector version to add custom health check and Poll interval delay

package.json, paws_utils.js
Currently  we keep minimum 10 min delay and it increase up to 30 min as we keep 60sec interval after each call.
If interval increase more than 15 min then we make set 1secs interval for each call.
=> Poll interval delay should not increased more than 15 min

collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/test.js, collectors/gsuite/package.json, collectors/gsuite/test/gsuite_test.js, collectors/mimecast/package.json, collectors/o365/package.json, collectors/o365/test/o365_test.js, collectors/okta/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json
- Poll interval delay  should not goes more than 15 min [pr](https://github.com/alertlogic/paws-collector/pull/217)
- Bump the all paws collector version except (auth0,Salesforce  and Sophossiem )collector as this collector not using calcNextCollectionInterval method to calculate pollInterval.
=> Bump the all paws collector version for pollIntervalDelay

cfn/paws-collector.template, package.json, paws_collector.js, test/paws_test.js
Deduplication DDB table doesn't help when collector state doesn't change because MD5 hash of a message is used as DDB item key.
Use unique message id as dedup table key instead of md5 hash.
=> Use unique message ID as dedup table key

collectors/o365/healthcheck.js, collectors/o365/lib/o365_mgmnt/index.js, collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/o365/test/o365_test.js
Made the multiple call to SSM to get credentials and some time it will take time/face issue to return the credentials .
So we get error `Error: secret must be a non empty string` .
1. Remove the PawsCollector.load() call from getO365ManagmentClient() to reduce the multiple call to SSM param.
2. Save the paws credentials in one object  when constructor get call and pass to O365 api from different  method (getPreFormedUrl, subscriptionsContent).
=> [o365]: Reduce the multiple SSM call to get credentials 

collectors/carbonblack/themis-template/carbonblackaudit.json, collectors/carbonblack/themis-template/carbonblackevents.json
Getting the error while Validating the carbonblack collector using themis template.
ex. `error: function_clause, trace: [{lhttpc_lib,split_scheme,["/appservices/v6/orgs/N2MF5397/alerts/search_suggestions?suggest.q="],[{file,"/codebuild/output/src578981762/src/algithub.pd.alertlogic.net/defender/themis/_build/default/lib/lhttpc/src/lhttpc_lib.erl"}`
Update the template to use correct field from themis data object and form the valid URL to authenticate the carbonblack credentials .
ex. data we get from themis data object is as below `data: #{<<"**client_id**">> => <<"J8KFCTQW74">>,<<"**collector_param_string2**">> => <<"N2MF5397">>,<<"collector_streams">> => <<"[\"SearchAlertsWatchlist\",\"SearchAlertsCBAnalytics\",\"SearchAlerts\"]">>,<<"collector_type_name">> => …
=> Carbonblack : Updated the carbon black Themis template to assign the value from themis data object

package.json
All paws deployment failed as updateFunctionConfiguration calls may fail if Lambda status is InProgress.
Fix in al-aws-collector-js. [pr](https://github.com/alertlogic/al-aws-collector-js/pull/72 )
=> [Paws lib]: Bump the paws version to fix Lambda.updateFunctionConfiguration failures

package.json, paws_collector.js, test/paws_test.js
For 0365 we getting the error `secret must be a non empty string.`.
After read the credentials from SSM we stored it in file in base64 format. 
Here is the Scenario when base64 value get set to secret instead of actual string :  When credentials file is exist and PAWS_DECRYPTED_CREDS  is empty ,it will check for ssm-direct and if it  true then we directly set that value as [secret](https://github.com/alertlogic/paws-collector/blob/master/paws_collector.js#L72) which is base64 format and not a  actual string.
Base on ssm-direct value(if true) stored the credentials in utf-8 format else stored in base64.
=> Paws-Lib Correct the file encoding format if ssm-direct is true

package.json, paws_collector.js
If file read in bas64 encoding format and pass the value for decryption it will return invalid cipher-text error.
Read buffer string and pass to kms decrypt to get actual value.
=> Cipher text should be in buffer string format

collectors/auth0/auth0_collector.js, collectors/auth0/package.json, collectors/auth0/test/auth0_test.js, collectors/ciscoduo/collector.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_test.js
Throttling error for Cisco duo and Auth0.
Error sample from Cisco duo collectors :
`PAWS000304 Error handling poll request: {\"code\":42901,\"message\":\"Too Many Requests\",\"stat\":\"FAIL\",\"errorCode\":42901}`
If we run into a rate limit/throttling error, instead of returning the error, we return the state back to the queue with an additional second.
1. Auth0 : Reference documents  for [ Auth0 Management API Endpoint Rate Limits](https://auth0.com/docs/support/policies/rate-limit-policy/management-api-endpoint-rate-limits). As per doc 10 api call per sec , but still added the 10 sec interval for safer side.
2. CiscoDuo : There is no proper document ,so refer the [ Cisco community doc](https://community.duo.com/t/429-too-many-requests-after-a-request-every-20-seconds/6863)  and added …
=> [Auth0 and Cisco Duo Collectors] : Handle the Throttling/ Rate limit error

collectors/ciscoduo/collector.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_test.js
Initially added 60  sec as poll interval if throttling issue occurs, But issue is not resolved completely .
Incremented the poll interval sec by 60 sec every time until MAX_POLL_INTERVAL(900 sec) reached.
So first time it will add 120 second and later on it will add 60 sec every time till 15 min as poll interval.
=> [Cisco Duo collector ]: Increment the poll interval by 60 sec for throttling issue

package.json, paws_utils.js
DD show collection delay increase for couple of collector. Below is the one of the reason to increase the collection delay.
Customer can add the  any collection start date from UI, so seen some customer added the long back date(year ago). 
But ingest will accept only last 30 days data. We are unnecessary making the so many API call .
If collection start date greater than 30 days, So adjust the start collection to last 30 days.
=> [Paws Utility] : Collection start date gt than 30 days, then adjust the date to last 30 days

collectors/googlestackdriver/collector.js, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/test.js
Getting the Throttling error  with message size greater than 4 MB from GCP collector.
` Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4518352 vs. 4194304)`
First reduce the interval into half and if not resolved for less than 15 sec then reduce the page size to half and pull the data.
=> [Googlestack driver] : Handle the GCP throttling error with max message size 4MB 

package.json, paws_collector.js, test/paws_test.js
Cost saving.
Remove unused `PawsClientOK` metric.To some extent it can we replaces with successful lambda invocation metrics.
=> Remove PawsClientOK metric as unused

collectors/okta/package.json
Update dependencies to support shared SNS triggers for checkins and updates. Please note old CW events triggers will continue to work until  (`paws-collector-shared.temaplte`)[https://github.com/alertlogic/paws-collector/blob/master/cfn/paws-collector-shared.template] is changed to support SNS triggers.
=> [Okta] Add shared SNS trigger support

collectors/collector.mk
Dev packages are included in the built zip packages
- Update collector.mk to run `npm prune --production` before creating the package
- Any target depending on `node_modules` will always trigger `npm install`
=> Exclude devDependencies from package builds

collectors/carbonblack/themis-template/carbonblackaudit.json
CarbonBlack credential validation fails due to deprecated `/events` endpoint
Update CB endpoint we use for credential validation
=> Fix CarbonBlack credential validate endpoint

collectors/ciscoduo/collector.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_test.js
Customer still able to see a couple of Rate limit error in every 15 min.
{
"code": 42901,
"level": "warn",
"message": "CDUO000003 API Request Limit Exceeded Too Many Requests",
"requestId": "8113cfaf-1017-5472-934f-94007e9d9c91",
"stat": "FAIL",
"timestamp": "2022-09-29T09:59:48.937Z"
}
RootCouse:
If collector is lacking behind more than 15 min it will make a api call every secs.
AS per [doc](https://duo.com/docs/adminapi#authentication-logs)(`We recommend requesting logs no more than once per minute`.)  i.e make api call one pr minutes .
So updated the poll interval sec to 60sec from 1sec.
=> [Cisco Duo collector] Increase the poll Interval secs from 1 to 60 sec

collectors/ciscoamp/collector.js, collectors/ciscoamp/package.json, collectors/ciscoamp/test/ciscoamp_mock.js, collectors/ciscoamp/test/ciscoamp_test.js, collectors/ciscoamp/test/utils_test.js, collectors/ciscoamp/utils.js
1. Customer having CiscoAMP collector and its Event stream not moving collection windows(lacking behind almost 1 and half month)
Root Cause :
-  When we make the api call for particular timestamp(`Events from 2022-07-30T00:00:00.000Z till 2022-07-30T00:00:57.000Z`),every time total log counts are different for same time interval. As per previous code we are discarding the logs if it not match with previous count stored in state object. So collection window not get updated .
"results": {
**"total": 131625,**
"current_item_count": 500,
"index": 500,
"items_per_page": 500
}
1. Cisco AMP API only have startDate (https://api.amp.cisco.com/v1/events?**start_date**=2022-09-19T00%3A00%3A00.000Z) and not end time stand, so total count will vary. APIs return the data in descending order by default …
=> CiscoAMP collector[1.0.34] : Refactor the code for Event stream and Throttle Error

collectors/o365/o365_collector.js, collectors/o365/package.json
Include `hostname` as `collector_id` into log messages in order to make incident deployment resolution work.
=> Add collector id as hostname into o365

cfn/paws-collector-shared.template, package.json, paws_collector.js, test/paws_mock.js, test/paws_test.js
Problem Description
Few collector facing collection delay because ingest service returning 400-'body encoding invalid'.
If ingest return body encoding invalid error then collector store the data in s3 bucket and allow collector to collect data for next collection window.
- This will help collector to avoid collection delay .
- We can also analyse the data later and accordingly we can take action if need.
Code changes :
1. Created new s3 bucket  to upload the file and Required write permission to upload/add file in s3 bucket. Added permission in alertlogic-collector-lambda-policy  of paws shared resources template. Reference [pr paws-collectors-deployment-pipeline](https://algithub.pd.alertlogic.net/defender/paws-collectors-deploy-pipeline/pull/413)
2. Mapped the dlS3bucket ARN in …
=> Upload the body encoding invalid data to s3 bucket and collector continue for next collection without any delay

package.json, paws_collector.js
Currently PawsIngestApi metrics showing errorCode : 'unknown` for All PAWS collectors.
Solution Description
Extracting the http status code from ingest message and sending to PawsIngestApi . It help to check which all ingest error collector getting. [extract error code from ingest error message](https://github.com/alertlogic/al-aws-collector-js/pull/88)
=> Used httpErrorCode to show actual error on Ingest metrics

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/mimecast/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
- Upload the body encoding invalid data to s3 bucket and collector continue for next collection without any delay.[pr](https://github.com/alertlogic/paws-collector/pull/316)
- Used httpErrorCode to show actual error on Ingest metrics . [pr](https://github.com/alertlogic/paws-collector/pull/317)
=> [All PAWS Collectors]Bump the package version to handle collection delay due to ingest bad encoding error

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/mimecast/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
Releasing below changes
- BucketName getting undefined as parameter name not matched [here](https://github.com/alertlogic/al-aws-collector-js/blob/master/health_checks.js#L138) [fixpr](https://github.com/alertlogic/al-aws-collector-js/pull/92)
- NPM vulnerabilities in paws-collector fixes [pr](https://github.com/alertlogic/paws-collector/pull/320)
=> Bump the package version for all collectors

package.json, paws_collector.js
Cisco duo collector use epochs unix time stamp ,so converted it from seconds to milliseconds to get correct date and collection delay second.
=> Converted the time from second to milliseconds to get correct date and collection delay secs

collectors/ciscoduo/collector.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_test.js, collectors/ciscoduo/test/utils_test.js, collectors/ciscoduo/utils.js
1. Few collector still facing throttle issue.
2. CiscoDuo collector not reporting collection delay metrics on DD
- Cisco duo api allow 1 api call per min. So we increasing poll interval delay base on number of stream.
If there are 4 stream then each stream call after 4 min.
- Update state message and added since and until so that Paws lib will picked it value to calculate collection delay.
=> Update poll-Interval base on number of stream and update the state message.

collectors/o365/o365_collector.js, collectors/o365/package.json, collectors/o365/test/o365_mock.js, collectors/o365/test/o365_test.js
o365 Management Api returning duplicate log which result in duplicate incident.
- AL plan to handle duplication of logs for 24 hr window by default.
- If we have to modify the window for any collector then add the `expire_ttl_hours` in ambda environment variable and set the value in hrs.
Refer the main change in paws_lib -[pr](https://github.com/alertlogic/paws-collector/pull/326)
=> [o365 Collector] Remove the duplicate logs for o365 collector

package.json, paws_collector.js, test/paws_test.js
Collector get the data from api and stored the data in DDB before sending to ingest. if ingest send any error then collector tried the same , again after some time ; as data is already present in DDB ,so it mark all the data as duplicate. We are loosing data here.
- Delete those entry from ddb which got error from ingest service while sending `/data/logmsgs`.
- Return the original error back to collector ,so that it will add same state in SQS message to retry again for fail state.
- Change the expire_ttl_hours to seconds ,so that it easy to set value in seconds from env variable rather than converting from hr to seconds.
=> [o365 Collector]: Handle the ingest error introduce due to deduplication changes

collectors/o365/package.json
Handle the ingest error introduce due to deduplication changes [pr](https://github.com/alertlogic/paws-collector/pull/330)
=> [o365 Collector]: Updated the Paws-lib latest version in o365 collector to handle ingest error

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/mimecast/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
Updated all collector to pick latest paws lib version 2.1.16 which handle deduplication issue for o365 collector.
=> [All Paws Collector]:Bump the all collector version to latest paws-lib 2.1.16  version

package.json, paws_collector.js, test/paws_test.js
Stop sending status to ingest directly. [al-aws-collector pr](https://github.com/alertlogic/al-aws-collector-js/pull/93)
Sending collector status to collector status service and it send to ingest.
- Replace the sendStatus method with sendCollectorStatus which send the status to collector status service.
- Send the streamType directly which will be set as stream while sending to collector status service
=> [ENG-43649 - Paws lib ] Send the status to collector_status service

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/mimecast/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
Send the status to collector_status service instead of ingest service [pr](https://github.com/alertlogic/paws-collector/pull/333)
=> [All Paws collectors] : Bump the package version to send the status to collector_status service 

collectors/auth0/package.json, collectors/carbonblack/package.json, collectors/ciscoamp/package.json, collectors/ciscoduo/package.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/package.json, collectors/gsuite/package.json, collectors/mimecast/package.json, collectors/o365/package.json, collectors/okta/package.json, collectors/salesforce/package.json, collectors/sentinelone/package.json, collectors/sophos/package.json, collectors/sophossiem/package.json
- Collector status return 409 if time stamp conflict.
- To avoid error status code 409, sending time stamp in milliseconds instead of seconds .
- Report the status to DD metrics to check which status we are sending to collector_status service.
=> [All Paws collectors]Bump the version to send the timestamp in millisecond and also send the status to DD metrics

package.json, paws_collector.js, test/paws_test.js
1. Collector service return 501 error while validating url because stream contain / which is not excepted
2. If there is any error ; collector send the new SQS message and after that if it fail to exit with lambda succeed because of time constraint. Then there will be duplication of SQS message as lambda not deleted the old one.
1.Encode the stream value while making the api call.
2. By default value of maxRetryTime is forever , so updating it to 3min . Refer [pr](https://github.com/alertlogic/al-aws-collector-js/pull/95)
3. Also execute the lambda context.succeed if lambda time remaining is less the 10sec.
=> [Paws lib] : Encoded the stream and handle the duplication of sqs message issue due to lambda timeout

collectors/auth0/package.json, collectors/auth0/test/auth0_mock.js, collectors/auth0/test/auth0_test.js, collectors/carbonblack/package.json, collectors/carbonblack/test/carbonblack_mock.js, collectors/ciscoamp/package.json, collectors/ciscoamp/test/ciscoamp_mock.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_mock.js, collectors/crowdstrike/package.json, collectors/crowdstrike/test/crowd-strike-mock.js, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/mock.js, collectors/gsuite/package.json, collectors/gsuite/test/gsuite_mock.js, collectors/mimecast/package.json, collectors/mimecast/test/mimecast_mock.js, collectors/o365/package.json, collectors/o365/test/o365_mock.js, collectors/okta/package.json, collectors/okta/test/okta_mock.js, collectors/salesforce/package.json, collectors/salesforce/test/salesforce_mock.js, collectors/sentinelone/package.json, collectors/sentinelone/test/sentinelone_mock.js, collectors/sophos/package.json, collectors/sophos/test/sophos_mock.js, collectors/sophossiem/package.json, collectors/sophossiem/test/sophossiem_mock.js
Bump the package version for stream encode and SQS duplication due to lambda timeout . Refer [pr](https://github.com/alertlogic/paws-collector/pull/338)
=> [All Paws collectors] : Bump the all package version for stream encode and handle SQS duplication.

collectors/okta/okta_collector.js, collectors/okta/package.json, collectors/okta/test/okta_test.js
In integration we have seen lots of okta collectors facing throttle error which result in increasing AWS cost.
Instead of returning throttle error ,now it return the same state with some poll interval delay .
- if we get the x-rate-limit-reset from header ,then add 60sec as extraBufferSeconds with reset and set the delaySecs.
- else set delaySecs by adding 60 secs with existing poll interval seconds and try adding thill max 15min delay
=> [Okta collector]: Handle the throttle error

package.json
AWS Inspector shows latest vulnerabilities with Lambda function requires node package updates(request package) for findings to fix.
- Replace request package with axios -https://github.com/alertlogic/al-collector-js/pull/57
- Al-aws-collector updated with latest changes of axios -https://github.com/alertlogic/al-aws-collector-js/pull/96
- Removed agentStatus method and added validation for collectors_status service call https://github.com/alertlogic/al-aws-collector-js/pull/97
=> ENG-50123: Replace the request package with axios for REST api call

collectors/auth0/local/sam-template.yaml, collectors/auth0/package.json, collectors/carbonblack/local/sam-template.yaml, collectors/carbonblack/package.json, collectors/ciscoamp/local/sam-template.yaml, collectors/ciscoamp/package.json, collectors/ciscoduo/local/sam-template.yaml, collectors/ciscoduo/package.json, collectors/crowdstrike/local/sam-template.yaml, collectors/crowdstrike/package.json, collectors/googlestackdriver/local/sam-template.yaml, collectors/googlestackdriver/package.json, collectors/gsuite/local/sam-template.yaml, collectors/gsuite/package.json, collectors/mimecast/local/sam-template.yaml, collectors/mimecast/package.json, collectors/o365/local/sam-template.yaml, collectors/o365/package.json, collectors/okta/local/sam-template.yaml, collectors/okta/package.json, collectors/salesforce/local/sam-template.yaml, collectors/salesforce/package.json, collectors/sentinelone/local/sam-template.yaml, collectors/sentinelone/package.json, collectors/sophos/local/sam-template.yaml, collectors/sophos/package.json, collectors/sophossiem/local/sam-template.yaml, collectors/sophossiem/package.json
AWS lambda runtime deprecated the node version 14
Update node version to 18. 
Added aws-sdk in dependancy as node 18 runtime does not provide aws-sdk complete module.Node 18 work with aws-sdk v3 and not v2 so explicitly adding aws-sdk which is required .
=> Bump the all paws-collectors version to upgrade node version to 18

collectors/auth0/al-auth0-collector.json, collectors/auth0/package.json, collectors/carbonblack/al-carbonblack-collector.json, collectors/carbonblack/package.json, collectors/ciscoamp/al-ciscoamp-collector.json, collectors/ciscoamp/package.json, collectors/ciscoduo/al-ciscoduo-collector.json, collectors/ciscoduo/package.json, collectors/crowdstrike/al-crowdstrike-collector.json, collectors/crowdstrike/package.json, collectors/googlestackdriver/al-googlestackdriver-collector.json, collectors/googlestackdriver/package.json, collectors/gsuite/al-gsuite-collector.json, collectors/gsuite/package.json, collectors/mimecast/al-mimecast-collector.json, collectors/mimecast/package.json, collectors/o365/al-o365-collector.json, collectors/o365/package.json, collectors/okta/al-okta-collector.json, collectors/okta/package.json, collectors/salesforce/al-salesforce-collector.json, collectors/salesforce/package.json, collectors/sentinelone/al-sentinelone-collector.json, collectors/sentinelone/package.json, collectors/sophos/al-sophos-collector.json, collectors/sophos/package.json, collectors/sophossiem/al-sophossiem-collector.json, collectors/sophossiem/package.json, collectors/template/collector.json, collectors/template/local/sam-template.yaml
Missed to push the collector.json file to upgrade  collectLambda function runtime node version from 14 to 18 in last [pr](https://github.com/alertlogic/paws-collector/pull/350)
=> Bump the version to update collect lambda function from node version 14 to 18

package.json, paws_collector.js, test/paws_stub.js, test/paws_test.js
Lambda Runtime nodejs 18 used aws-sdk v3 version 
- Upgrade collectors from aws-sdk version from v2 to v3
- update the functionality as per v3 version
- Fix the test cases.
- Removed aws-sdk and aws-sdk-mock both dependancy.
=> [ENG-52244]Upgrade collectors aws-sdk version from v2 to v3 and rewrite functionality and test cases

collectors/googlestackdriver/collector.js, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/test.js
Collector losses the data as state since and until value not set properly during pagination scenario.  
Example : If there is lots of pages and collector collected paws_max_pages_per_invocation(default -10) max pages in one call , if there is still nextPage token since and until value should not change but currently it changes after every call . So if there is no more page it will start collecting the until value which is latest. Hence it lost the data for some period
If nextPage available then don’t change since & until value only update next_token else update the since and until pass in next filter.
=> ENG-53369 : GCP collector - Handle the pagination state properly

package.json, paws_collector.js, test/paws_test.js
1.Some time there are big messages ,so collector face max playload issue and not able to proceed further. Which may cause delay in collection or some time loss the data if customer not reached out to us for long time. 
Currently we have to manually reduce the max pages from environment variable.
2. With aws-sdk v3 version lambda retry mechanism is break as variable name got change in sdk v3.
1. If we get the max payload issue ,we split the current batch in to multiple small batches and send the data to ingest.
so no manual intervention required.
2. Fix the variable name as per aws-sdk v3 and update the library .-https://github.com/alertlogic/al-aws-collector-js/pull/103
=> ENG- 53314 : Handle the max payload exceeded error

collectors/carbonblack/collector.js, collectors/carbonblack/package.json, collectors/carbonblack/test/utils_test.js, collectors/carbonblack/themis-template/carbonblackevents.json, collectors/carbonblack/utils.js, ps_spec.yml
Alert V6 API will be deactivated on July 31, 2024.
Migrating to alert api v7 .
The observation Alerts have been removed from the v7 Alerts API and available under [Observations](https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/observations-api/) api
1. For now we only migrated the alert api to v7 version.
a. Change the variable name as per [alert api migration](https://developer.carbonblack.com/reference/carbon-black-cloud/guides/api-migration/alerts-migration) document .
b. Updated the api url and request body
c. Updated the themis template json as per api v7[ search recommendation
](https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/alerts-api/#get-search-recommendations)
2. Configure observations api and  get observation will be …
=> ENG-50794: Update to version v7 from v6 for Alerts API

collectors/googlestackdriver/collector.js, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/test.js, ps_spec.yml
During throttling, we increase the poll interval and decrease the time duration. However, when the collector is collecting data through pagination, it already sets the filter timestamp (timestamp >= since and timestamp < until). The actual until value changes in the state during throttling. Once pagination completes and the collector creates a new state, it starts again from the same timestamp, resulting in duplicate data collection.
ex. In below state example until value(i.e 2024-05-25T10:39:49.000Z) in filter and actual(i.e 2024-05-24T10:39:50.000Z) is different.
`{"priv_collector_state":{"since":"2024-05-24T10:39:49.000Z","nextPage":{"filter":"timestamp >= \"2024-05-24T10:39:49.000Z\"\ntimestamp < \"2024-05-25T10:39:49.000Z\"","pageSize":1000,"resourceNames":["projects/prj-mstr-prod"]," …
=> ENG-55392-Googlestackdriver collector: Handle the throttle error for pagination scenario

package.json, paws_utils.js
The Cisco collector uses an hourly cap to catch up on backlog data. However, it only allows one call per minute, so it will never be able to catch up to the current time. This can add a delay of more than 2 hours when the delay condition (hour delay > 1) is met. Customers do not want delays in data collection.
Added an equals condition so that it will collect data for one hour directly if the delay goes to more than or equal to 1 hour. This will reduce the delay to a maximum of 1 hour.
=> update the hour-cap condition to collect if delay is 1 hr or greater

collectors/ciscoduo/collector.js, collectors/ciscoduo/package.json, collectors/ciscoduo/test/ciscoduo_test.js, ps_spec.yml
The customer is experiencing two delays in collecting Cisco Duo logs.
Reduce the poll interval from 4 minutes (previously based on the number of streams) to 1 minute.
Change the condition to catch up if the collection delay is greater than or equal to 1 hour. [pr](https://github.com/alertlogic/paws-collector/pull/374)
According to the[ Cisco duo api doc](https://duo.com/docs/adminapi#authentication-logs)   it is recommended to make only one API call per minute. Therefore, we cannot catch up quickly, and there might be a delay of up to 1 hour, but not more than that.
=> Updated the poll interval to reduce delay and handle throttle

package.json, paws_collector.js
Getting below warning from DDB while  writing item in table.
`@smithy/node-http-handler:WARN socket usage at capacity=50 and 9753 additional requests are enqueued. See https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-maxsockets.html or increase socketAcquisitionWarningTimeout=(millis) in the NodeHttpHandler config.`
Added maxSocket configuration as per on AWS doc
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-maxsockets.html
=> [ENG-55813]To handle max socket warning while writing the item on DDB

package.json, paws_collector.js
] AWS inspector showing Vulnerabilities for our lambda functions and fix ddb warnings and performance by making a single static DDB client.
1. AWS inspector vulnerabilities fixed.
2. Created a single static DDB client Object to improve performance.
=> AWS inspector vulnerabilities and ddb warning fixes by making a single static DDB client

collectors/googlestackdriver/cfn/googlestackdriver-collector.template, collectors/googlestackdriver/collector.js, collectors/googlestackdriver/package.json, collectors/googlestackdriver/test/test.js, ps_spec.yml
Currently there is no functionality to filter the logs base on log names and collector pull all type of logs
Apply filtering based on the provided logName values,
So that the system fetches only the relevant logs, or all logs if no logName is provided, using the GCP Logging API.
1. Filter Handling: 
- The backend should receive the logName filter value from the UI.
- If one or more logName values are provided, the backend should apply these filters when making requests to the GCP Logging API.
It will encode the Log name URI if it is not encoded. It will accept below pattern :
1.`cloudaudit.googleapis.com%2Factivity`;
2. `cloudaudit.googleapis.com/activity`;
3. `cloudaudit.googleapis.com%2Factivity\ncloudaudit.googleapis.com%2Factivity-function`; // Valid multiple entries
4. …
=> [GCP ]Filter the logs base on logNames and timestamps

collectors/ciscomeraki/collector.js, collectors/ciscomeraki/package.json, ps_spec.yml
Cisco Meraki collector fetch the data from all the networks from his Cisco Meraki organisations . For customers there may be some networks which doesn't  have product types selected or asisgned and collector try to fetch the data for the selected product type(["appliance","wireless","switch"), ,hence it returning error as below for few networks.
`
"productType is not applicable to this network"`
To address this, we plan to stop sending error messages for cases where the API returns errors: ["productType is not applicable to this network"], as there is nothing to collect in such scenarios. Consequently, no remediation will be shown in the health console.
Instead, we will log a warning in AWS CloudWatch logs to indicate which networks do not have any product types. This warning will help …
=> [Cisco Meraki] Add warning message productType is not applicable to this network and skip collecting logs in cisco meraki collector

collectors/ciscomeraki/collector.js, collectors/ciscomeraki/meraki_client.js, collectors/ciscomeraki/package.json, ps_spec.yml
When the error "productType is not applicable to this network" occurs and is caught and thrown, the collector not collecting data for other product types associated with the network.
Improved Error handling in cisco meraki collector to ensure continuous data collection even if productType is not applicable to networks
=> [Cisco Meraki] Improve Error handling in cisco meraki collector

collectors/ciscomeraki/collector.js, collectors/ciscomeraki/meraki_client.js, collectors/ciscomeraki/package.json, collectors/ciscomeraki/test/meraki_client_test.js, ps_spec.yml
Duplicate data is sent to ingest because of state.since not updating properly in cisco meraki collector
Modified code to updates state.since not updating properly by removing returing accumulator logic.
=> [Cisco Meraki] Duplicate data is sent to ingest because of state.since not updating properly in cisco meraki collector

cfn/paws-collector-shared.template
By default, CloudWatch log groups were created with "Never Expire", leading to uncontrolled storage growth and unnecessary costs.
Use the AWS CloudFormation (CFN) to automate the process and update the retention period to 13 Month while create cloud watch group.
=> [ENG-57488]:Added the retention period to 13 month for cloud watch log group

cfn/paws-collector-shared.template
If we delete a CloudFormation (CFN) stack, it will delete all its resources. We need to retain CloudWatch log groups to review logs from failed stacks.
Added a DeletionPolicy of Retain for CloudWatch log groups to prevent their deletion.
`"DeletionPolicy": "Retain"`
=> [ENG-57488] Added the retention period to 13 month for cloud watch log group

collectors/sophossiem/package.json, collectors/sophossiem/themis-template/sophossiem.json, ps_spec.yml
As per Sophos Central API [documentation](https://support.sophos.com/support/s/article/KBA-000004438?language=en_US), the legacy API Token Management is being retired. Existing tokens will remain functional until expiration, but new tokens cannot be created or renewed. Moving forward, authentication will require Api credential management authentication using Client ID and Client Secret instead of direct API tokens.
Themis service validating for Sophos Siem collector through template https://algithub.pd.alertlogic.net/defender/themis/blob/837f1f2fa83381a9f9f20c7bb36d614cbc09502f/src/themis_paws_validator.erl#L23
Validation done through template using validate_paws_with_template . So updated the themis template to support API credential validation using client_id and client secret.
=> [ENG-57829]Themis service validation- Sophos Siem Collector ]: API Token setup EOL

collectors/crowdstrike/cfn/crowdstrike-collector.template, collectors/crowdstrike/collector.js, collectors/crowdstrike/package.json, collectors/crowdstrike/test/crowd-strike-mock.js, collectors/crowdstrike/test/crowd-strike-test.js, collectors/crowdstrike/test/utils-test.js, collectors/crowdstrike/utils.js, ps_spec.yml
The Detection API endpoints are deprecated and will be decommissioned on September 30th, 2025. The Alerts api is provide Legacy concepts, so migrated to Alerts API.
Added support to collect detection data using the Alerts API. The existing Detection API code can be removed if it begins to fail or once it is officially(i.e. September 30th, 2025) deprecated.
To retrieve alert details, use the following APIs:
1. Query Alert IDs
GET /alerts/queries/alerts/v2
Use filters such as `project:epp` and `created_timestamp` to identify relevant alert IDs.
2. Fetch Alert Details
POST /alerts/entities/alerts/v2
Use the retrieved alert IDs to get detailed information about each alert.
1. Alerts API Integration
2. Existing Detection API code should remain functional but be clearly marked as deprecated.
3. …
=> [ENG-58761]:Migrate detect API to Alerts
